settings:
    # Jira project key to create the issue in
  jira_project_key: "PBTAR"
  
  # Dictionary mapping GitHub issue status to Jira issue status
  status_mapping:
    opened: Backlog
    closed: Done
    not_planned: Declined
      
  # (Optional) GitHub labels. Only issues with one of those labels will be synchronized.
  # If not specified, all issues will be synchronized
  labels:
    - jira
      
  # (Optional) (Default: false) Add a new comment in GitHub with a link to Jira created issue
  add_gh_comment: true

  # (Optional) (Default: false) Add a 'synced-to-jira' label to newly created issues once a
  # corresponding ticket is successfully created in Jira.
  # This label serves as confirmation that the issue sync process was completed successfully.
  add_gh_synced_label: false
  
  # (Optional) (Default: true) Synchronize issue description from GitHub to Jira
  sync_description: true
  
  # (Optional) (Default: true) Synchronize comments from GitHub to Jira
  sync_comments: false
  
  # (Optional) (Default: None) Parent Epic key to link the issue to
  epic_key: "PBTAR-3"
      
  # (Optional) Dictionary mapping GitHub issue labels to Jira issue types. 
  # If label on the issue is not in specified list, this issue will be created as a Bug
  label_mapping:
    jira: Story
