version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directories:
      - "/api"
      - "/database"
      - "/frontend"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
