version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/api"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directories:
      - "/api"
      - "/database"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
