
services:
  api:
    build:
      context: api
    environment:
      - PBTAR_API_KEY=${PBTAR_API_KEY:-abc123}
      - PBTAR_API_PORT=${PBTAR_API_PORT:-8080}
      - PBTAR_DB_PORT=${PBTAR_DB_PORT:-5432}
      - PYTHONUNBUFFERED=1
    container_name: pbtar-api
    ports:
      - "80:${PBTAR_API_PORT:-8080}"
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pbtar
    ports:
      - "${PBTAR_DB_PORT:-5432}:${PBTAR_DB_PORT:-5432}"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: frontend
    ports:
      - "${PBTAR_FRONTEND_PORT:-3000}:80"
    environment:
      - VITE_API_URL=http://api:${PBTAR_API_PORT:-8080}
    container_name: pbtar-frontend
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local
