/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines which greenhouse gases are covered in the pathway's modeled emissions.
 */
export type EmissionsScopeV1 =
  | "No information"
  | "CO2"
  | "CO2e (Kyoto)"
  | "CO2e (CO2, Methane)"
  | "CO2e (unspecified GHGs)"
  | "Other emissions scope";
