/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Label object with optional abbreviation.
 */
export interface LabelV1 {
  /**
   * Full name or label
   */
  full: string;
  /**
   * Short name, acronym, or abbreviation
   */
  short?: string;
}
