/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Line-oriented Markdown. Each array element is one Markdown line. Use "" for a blank line. Renderer will collapse consecutive blanks and ensure one blank line after ATX headers.
 *
 * @minItems 1
 * @maxItems 1000
 */
export type MarkdownV1 = [
  (
    | ({
        [k: string]: unknown;
      } & {
        [k: string]: unknown;
      } & string)
    | ""
    | string
    | string
    | string
  ),
  ...(
    | ({
        [k: string]: unknown;
      } & {
        [k: string]: unknown;
      } & string)
    | ""
    | string
    | string
    | string
  )[]
];
