/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Title of the report or publication.
 */
export type Label = import("./label.v1").LabelV1;
/**
 * Publisher or organization responsible for the publication.
 */
export type Label1 = import("./label.v1").LabelV1;

/**
 * Bibliographic information about the report or dataset.
 */
export interface PublicationV1 {
  title: Label;
  /**
   * Optional subtitle of the publication.
   */
  subtitle?: string;
  /**
   * List of authors or contributors.
   */
  author?: string[];
  publisher: Label1;
  /**
   * Year of publication.
   */
  year: number;
  /**
   * Month of publication (1–12).
   */
  month?: number;
  /**
   * Day of publication (1–31).
   */
  day?: number;
  /**
   * City where the publication was published.
   */
  city?: string;
  /**
   * Digital Object Identifier for the publication.
   */
  doi?: string;
  /**
   * International Standard Book Number, if applicable.
   */
  isbn?: string;
  /**
   * International Standard Serial Number, if applicable.
   */
  issn?: string;
  /**
   * License under which the document is published
   */
  license?: string;
  /**
   * Links to related materials such as data, supplementary files, or the full report.
   */
  links?: {
    /**
     * Short label for the linked resource.
     */
    description?: string;
    /**
     * URL to the linked resource.
     */
    url: string;
  }[];
}
