/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Display name of the technology as presented in charts or tables.
 */
export type DisplayName =
  | "Precision Agriculture"
  | "Agroforestry"
  | "Bioenergy Crops"
  | "Energy Efficiency"
  | "Smart Grids"
  | "Renewable Heating"
  | "Heat Pumps"
  | "Building Automation"
  | "Smart Appliances"
  | "Insulation"
  | "Carbon Capture and Storage"
  | "Electrification"
  | "Process Optimization"
  | "Hydrogen Use"
  | "Coal"
  | "Oil"
  | "Gas"
  | "Wind"
  | "Solar"
  | "Nuclear"
  | "Biomass"
  | "Hydro"
  | "Renewables"
  | "Electric Vehicles"
  | "Hydrogen Vehicles"
  | "Biofuels"
  | "Public Transport"
  | "Active Mobility"
  | "Aviation Efficiency"
  | "Maritime Efficiency"
  | "Other";

/**
 * Technologies for sectors
 */
export interface TechnologyV1 {
  displayName: DisplayName;
}
