/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bibliographic information about the report or dataset.
 */
export type Publication = import("./publication.v1").PublicationV1;

/**
 * A schema for the pathway metadata dataset in PBTAR.
 */
export interface PathwayMetadataV1 {
  /**
   * URI of the schema that validates this document (see https://json-schema.org/).
   */
  $schema?: string;
  /**
   * The unique identifier for a pathway.
   */
  id: string;
  /**
   * Name of the pathway.
   */
  name: string;
  /**
   * Brief description of the pathway.
   */
  description: string;
  publication: Publication;
  /**
   * Type of the pathway pathway.
   */
  pathwayType: "Normative" | "Exploratory" | "Direct Policy" | "Predictive";
  /**
   * Year by which net zero is reached in the pathway. If Pathway does not reach net zero, this field should be omitted.
   */
  modelYearNetzero?: number;
  /**
   * Carbon budget of the pathway in gigatons of CO2 equivalent (GtCO2eq). If no carbon budget is defined, this field should be omitted. If the carbon budget is not applicable, it should be set to 0.
   */
  carbonBudget?: number;
  /**
   * Year from which the model starts.
   */
  modelYearStart?: number;
  /**
   * Year in which the model ends.
   */
  modelYearEnd?: number;
  /**
   * Modeled temperature increase expected by the pathway (in degrees Celsius).
   */
  modelTempIncrease?: number;
  /**
   * Shared Socioeconomic Pathways (SSP) associated with the pathway.
   */
  ssp?: "SSP1" | "SSP2" | "SSP3" | "SSP4" | "SSP5";
  /**
   * Geographical areas that the pathway covers. Can include 'Global', country ISO-3166-1 alpha-2 codes (US, DE), or free-text region names (e.g., 'Europe', 'OECD'). Any 2-letter items in the array will be treated as an ISO code. Any 2-letter entries that do not map to a country will throw errors (EU). Do not use full country names, only ISO alpha-2 codes. To avoid typographical errors, items in this array may not be 3 letters long (USA)
   */
  geography: ({
    [k: string]: unknown;
  } & string)[];
  /**
   * Sectors that the pathway covers.
   */
  sectors: {
    name:
      | "Land Use"
      | "Agriculture"
      | "Buildings"
      | "Industry"
      | "Steel"
      | "Cement"
      | "Chemicals"
      | "Coal Mining"
      | "Oil (Upstream)"
      | "Gas (Upstream)"
      | "Power"
      | "Automotive"
      | "Transport"
      | "Road transport"
      | "Aviation"
      | "Rail"
      | "Shipping"
      | "Other";
    /**
     * Technologies applicable to this sector.
     */
    technologies: (
      | "Precision Agriculture"
      | "Agroforestry"
      | "Bioenergy Crops"
      | "Energy Efficiency"
      | "Smart Grids"
      | "Renewable Heating"
      | "Heat Pumps"
      | "Building Automation"
      | "Smart Appliances"
      | "Insulation"
      | "Carbon Capture and Storage"
      | "Electrification"
      | "Process Optimization"
      | "Hydrogen Use"
      | "Coal"
      | "Oil"
      | "Gas"
      | "Wind"
      | "Solar"
      | "Nuclear"
      | "Biomass"
      | "Hydro"
      | "Renewables"
      | "Electric Vehicles"
      | "Hydrogen Vehicles"
      | "Biofuels"
      | "Public Transport"
      | "Active Mobility"
      | "Aviation Efficiency"
      | "Maritime Efficiency"
      | "Other"
    )[];
  }[];
  /**
   * Overview of the pathway.
   */
  pathwayOverview?: string;
  /**
   * Expert recommendation for the pathway.
   */
  expertOverview: string;
  metric: (
    | "Emissions Intensity"
    | "Capacity"
    | "Generation"
    | "Technology Mix"
    | "Absolute Emissions"
  )[];
  /**
   * Key features of the pathway.
   */
  keyFeatures: {
    /**
     * Describes the overall trend of greenhouse gas emissions over time, from continued growth to rapid decline.
     */
    emissionsPathway:
      | "No information"
      | "Significant increase"
      | "Moderate increase"
      | "Minor increase"
      | "Low or no change"
      | "Minor decrease"
      | "Moderate decrease"
      | "Significant decrease";
    /**
     * Indicates how efficiently energy is used to produce economic output across the sectors covered in the pathway.
     */
    energyEfficiency:
      | "No information"
      | "Significant deterioration"
      | "Moderate deterioration"
      | "Minor deterioration"
      | "Low or no change"
      | "Minor improvement"
      | "Moderate improvement"
      | "Significant improvement";
    /**
     * Captures the change in total energy consumption, driven by factors such as socio-economic development, technology shifts and consumer behavior.
     */
    energyDemand:
      | "No information"
      | "Significant decrease"
      | "Moderate decrease"
      | "Minor decrease"
      | "Low or no change"
      | "Minor increase"
      | "Moderate increase"
      | "Significant increase";
    /**
     * Represents the extent to which energy end-uses transition from fossil fuels to electricity.
     */
    electrification:
      | "No information"
      | "Significant decrease"
      | "Moderate decrease"
      | "Minor decrease"
      | "Low or no change"
      | "Minor increase"
      | "Moderate increase"
      | "Significant increase";
    /**
     * Identifies the types of policies modeled as drivers of the pathway, such as carbon pricing, subsidies, or mandated phaseouts of specific technologies.
     *
     * @minItems 1
     */
    policyTypes: [
      (
        | "Carbon price"
        | "Phaseout dates"
        | "Subsidies"
        | "Target technology shares"
        | "Other"
        | "None"
      ),
      ...(
        | "Carbon price"
        | "Phaseout dates"
        | "Subsidies"
        | "Target technology shares"
        | "Other"
        | "None"
      )[],
    ];
    /**
     * Describes how technology costs evolve over time, from static cost assumptions to rapidly declining costs (e.g., via learning curves).
     */
    technologyCostTrend:
      | "No information"
      | "Increase"
      | "Low or no change"
      | "Decrease";
    /**
     * Indicates the scale and pace of new technology adoption within the pathway, where significant deployment means that several new technologies are adopted rapidly
     */
    technologyDeploymentTrend:
      | "No information"
      | "No new technologies deployed"
      | "Minor technology deployment"
      | "Moderate technology deployment"
      | "Signif. technology deployment";
    /**
     * Defines which greenhouse gases are covered in the pathway’s emissions accounting.
     */
    emissionsScope:
      | "No information"
      | "CO2"
      | "CO2e (Kyoto)"
      | "CO2e (CO2, Methane)"
      | "CO2e (unspecified GHGs)"
      | "Other emissions scope";
    /**
     * Represents the overall stringency and intent of modeled policies relative to climate targets, often reflecting if and how far the included policies go beyond currently legislated ones
     */
    policyAmbition:
      | "No information"
      | "No policies included"
      | "Current/legislated policies"
      | "Current and drafted policies"
      | "NDCs, unconditional only"
      | "NDCs incl. conditional targets"
      | "Normative/Optimization-based"
      | "Other policy ambition";
    /**
     * Specifies the level of granularity in cost data, such as total system costs or detailed CAPEX/OPEX breakdowns.
     */
    technologyCostsDetail:
      | "No information"
      | "Total costs"
      | "Capital costs, O&M, etc."
      | "Other cost breakdown";
    /**
     * Lists emerging or breakthrough technologies that are explicitly modeled within the pathway. These are considered in technology deployment too.
     *
     * @minItems 1
     */
    newTechnologiesIncluded: [
      (
        | "No information"
        | "No new technologies"
        | "CCUS"
        | "DAC"
        | "Green H2/ammonia"
        | "SAF"
        | "Battery storage"
        | "EGS/AGS"
        | "Other new technologies"
      ),
      ...(
        | "No information"
        | "No new technologies"
        | "CCUS"
        | "DAC"
        | "Green H2/ammonia"
        | "SAF"
        | "Battery storage"
        | "EGS/AGS"
        | "Other new technologies"
      )[],
    ];
    /**
     * Describes how upstream fuel or material price dynamics are represented in the pathway.
     */
    supplyChain:
      | "No information"
      | "Static input or fuel price"
      | "Exogenous input or fuel price"
      | "Endogenous input or fuel price";
    /**
     * Summarizes how investment requirements are quantified, from total system to sector-level or supply-chain detail.
     */
    investmentNeeds:
      | "No information"
      | "Total investment"
      | "By sector"
      | "By sector, part of value chain"
      | "By technology"
      | "By tech, part of value chain";
    /**
     * Describes how infrastructure buildout and maintenance needs are represented across the supply chain.
     */
    infrastructureRequirements:
      | "No information"
      | "By part of supply chain"
      | "By supply chain, add/replace";
  };
}
