/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bibliographic information about the report or dataset.
 */
export type Publication = import("./common/publication.v1").PublicationV1;
/**
 * Defines which greenhouse gases are covered in the pathway's modeled emissions.
 */
export type EmissionsScope =
  import("./common/emissionsScope.v1").EmissionsScopeV1;

/**
 * A schema for the pathway timeseries dataset in PBTAR.
 */
export interface PathwayTimeseriesV1 {
  /**
   * URI of the schema that validates this document (see https://json-schema.org/).
   */
  $schema?: string;
  /**
   * The unique identifier for a pathway.
   */
  id: string;
  /**
   * Identifiers of the associated pathways.
   */
  pathwayId: string[];
  /**
   * Name of the timeseries.
   */
  name: string;
  /**
   * Brief description of the timeseries.
   */
  description: string;
  publication: Publication;
  /**
   * Name of the associated pathway.
   */
  pathwayName: string;
  emissionsScope: EmissionsScope;
  /**
   * Sectors that the timeseries data covers.
   */
  sector: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[A-Za-z0-9 _-]{1,100}$".
     */
    [k: string]: {
      /**
       * Display name of the sector as presented in charts or tables.
       */
      displayName?:
        | "Land Use"
        | "Agriculture"
        | "Buildings"
        | "Industry"
        | "Steel"
        | "Cement"
        | "Chemicals"
        | "Coal Mining"
        | "Oil (Upstream)"
        | "Gas (Upstream)"
        | "Power"
        | "Automotive"
        | "Transport"
        | "Road transport"
        | "Aviation"
        | "Rail"
        | "Shipping"
        | "Other";
      /**
       * Technologies that belong to this sector, each with a name and definition.
       */
      technology?: {
        [k: string]: Technology;
      };
      /**
       * Metrics available for this sector, describing what quantities are tracked (e.g., capacity, emissions).
       */
      metric?: {
        [k: string]: Metric;
      };
    };
  };
  /**
   * Array of yearly data points for each sector, technology, and metric defined in this timeseries.
   */
  data: {
    [k: string]: unknown;
  }[];
}
/**
 * Technologies for sectors
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Za-z0-9 _-]{1,100}$".
 */
export interface Technology {
  /**
   * Display name of the technology as presented in charts or tables.
   */
  displayName:
    | "Precision Agriculture"
    | "Agroforestry"
    | "Bioenergy Crops"
    | "Energy Efficiency"
    | "Smart Grids"
    | "Renewable Heating"
    | "Heat Pumps"
    | "Building Automation"
    | "Smart Appliances"
    | "Insulation"
    | "Carbon Capture and Storage"
    | "Electrification"
    | "Process Optimization"
    | "Hydrogen Use"
    | "Coal"
    | "Oil"
    | "Gas"
    | "Wind"
    | "Solar"
    | "Nuclear"
    | "Biomass"
    | "Hydro"
    | "Renewables"
    | "Electric Vehicles"
    | "Hydrogen Vehicles"
    | "Biofuels"
    | "Public Transport"
    | "Active Mobility"
    | "Aviation Efficiency"
    | "Maritime Efficiency"
    | "Other";
  /**
   * Brief definition or description of the technology scope (e.g., what it includes or excludes).
   */
  definition: string;
}
/**
 * Common definition of a metric used across pathway schemas.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Za-z0-9 _-]{1,100}$".
 */
export interface Metric {
  /**
   * Display name of the metric
   */
  displayName:
    | "Emissions Intensity"
    | "Capacity"
    | "Generation"
    | "Technology Mix"
    | "Absolute Emissions";
  /**
   * Detailed description of what the metric represents.
   */
  definition: string;
  /**
   * Specifies which parts of the sector value chain the metric applies to.
   */
  sectorScope: string;
}
