---
on:
  pull_request:
    branches:
      - "hotfix/**"
      - "release/**"
      - main
      - production

name: Rulesets Checks
concurrency: rulesets-checks

jobs:
  rulesets:
    name: "Check GH rulesets"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get all existing Rulesets from Repo
        id: get-all-rulesets-repo
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api ${{ format('/repos/{0}/rulesets', github.repository) }} > /tmp/all_rulesets.json
          jq '.' /tmp/all_rulesets.json

          jq '[ .[] | .id ]' /tmp/all_rulesets.json > /tmp/ruleset_ids.json
          cat /tmp/ruleset_ids.json

      - name: Get Rulesets details from Repo
        id: get-rulesets-details-repo
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |

          mkdir /tmp/repo_rulesets
          jq -rc '.[]' /tmp/ruleset_ids.json | while read ID
          do
            echo "ID=$ID"
            gh api "/repos/RMI/pbtar/rulesets/$ID" | jq '.' > "/tmp/repo_rulesets/${ID}.json"
          done
