---
on:
  pull_request:
    branches:
      - "hotfix/**"
      - "release/**"
      - main
      - production

name: Rulesets Checks
concurrency: rulesets-checks

jobs:
  rulesets:
    name: "Check GH rulesets"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get all existing Rulesets from Remote Repo
        id: get-all-rulesets-remote
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api /repos/RMI/pbtar/rulesets > /tmp/all_rulesets.json
          jq '.' /tmp/all_rulesets.json

          jq '[ .[] | .id ]' /tmp/all_rulesets.json > /tmp/ruleset_ids.json
          cat /tmp/ruleset_ids.json

      - name: Get Rulesets details from Remote Repo
        id: get-rulesets-details-remote
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |

          mkdir /tmp/remote_rulesets
          jq -rc '.[]' /tmp/ruleset_ids.json | while read ID
          do
            echo "ID=$ID"
            gh api "/repos/RMI/pbtar/rulesets/$ID" | \
            jq 'del(
              .current_user_can_bypass,
              ._links,
              .node_id,
              .created_at,
              .updated_at,
              .bypass_actors
            )' \
            > "/tmp/remote_rulesets/${ID}.json"
            RULESET_NAME="$(jq -rc '.name' /tmp/remote_rulesets/${ID}.json)"
            echo "RULESET_NAME=$RULESET_NAME"
            mv "/tmp/remote_rulesets/${ID}.json" "/tmp/remote_rulesets/${RULESET_NAME}.json"
          done

      - name: Show Remote Repo Rules
        run: cat /tmp/remote_rulesets/*


      - name: Prepare local rulesets
        run: |

          mkdir /tmp/local_rulesets
          for FILE in .github/rulesets/*.json
          do
            ID="$(jq -rc '.id' $FILE)"
            RULESET_NAME="$(jq -rc '.name' $FILE)"
            echo "$FILE: $ID, $RULESET_NAME"
            jq 'del(.bypass_actors)' $FILE > "/tmp/local_rulesets/${RULESET_NAME}.json"
          done

      - name: Diff directories
        run: |

          diff \
            --recursive \
            --unified \
            --new-file \
            --color=auto \
            /tmp/remote_rulesets/ \
            /tmp/local_rulesets/
