---
on:
  workflow_call:

name: Azure Static Web Apps Close Environment

permissions:
  contents: read
  pull-requests: write

jobs:
  close_pull_request_job:
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_GLACIER_0F640931E }}
          action: "close"
          skip_deploy_on_missing_secrets: ${{ github.actor == 'dependabot[bot]' }}
