name: JSON validate Frontend service

on:
  push:
    branches:
      - production
      - main
    paths:
      - "pbtar_schema.json"
      - "src/data/scenarios_metadata.json"
      - ".github/workflows/frontend-json.yml"
  pull_request:
    branches:
      - "hotfix/**"
      - "release/**"
      - main
      - production
    paths:
      - "pbtar_schema.json"
      - "src/data/scenarios_metadata.json"
      - ".github/workflows/frontend-json.yml"
  workflow_dispatch:

jobs:
  lint:
    name: "Run ajv JSON validator"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ajv JSON validator
        run: npm run json:check
