name: Test Frontend service

on:
  push:
    branches:
      - production
      - main
  pull_request:
    branches:
      - "hotfix/**"
      - "release/**"
      - main
      - production
  workflow_dispatch:

jobs:
  test:
    name: "Run frontend unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check build
        run: npm run build
