---
name: Check GitFlow branch names

on:
  pull_request:
    branches:
      - production

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch name
        shell: bash
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          echo "Source branch: $BRANCH"

          if [[ "$BRANCH" == "next" || "$BRANCH" == "hotfix/"* ]]; then
            echo "Source branch allowed."
            exit 0
          else
            echo "::error::Only 'next' or 'hotfix/*' branches can be merged into production (got '$BRANCH')"
            exit 1
          fi
