---
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
      - production
      - next
  push:
    branches:
      - main
      - production
      - next

name: Node Package Checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: "Linting"
    if: ${{ !( github.event_name == 'pull_request' && github.event.action == 'closed' ) }}
    uses: ./.github/workflows/node-lint.yml

  formatting:
    name: "Formatting"
    if: ${{ !( github.event_name == 'pull_request' && github.event.action == 'closed' ) }}
    uses: ./.github/workflows/node-prettier.yml

  unit-test:
    name: "Unit Tests"
    if: ${{ !( github.event_name == 'pull_request' && github.event.action == 'closed' ) }}
    uses: ./.github/workflows/node-test.yml

  json-schema:
    name: "JSON Schema Validation"
    if: ${{ !( github.event_name == 'pull_request' && github.event.action == 'closed' ) }}
    uses: ./.github/workflows/node-json-schema.yml

  build-release:
    name: "Build and Release"
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/node-semantic_release.yml
    secrets: inherit

  build-pr:
    name: "Build"
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    uses: ./.github/workflows/node-semantic_release-pr.yml
    secrets: inherit

  deploy:
    name: "Deploy to SWA"
    needs: [build-release, build-pr]
    # always will trigger, and the "success" conditionals are there to ensure
    # that one or the other dependencies ran.
    if: ${{ always() && (needs.build-release.result == 'success' || needs.build-pr.result == 'success') }}
    uses: ./.github/workflows/azure-static-web-apps-deploy.yml
    secrets: inherit
