---
on:
  workflow_call:

name: Build and Release

permissions:
  contents: read # for checkout

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # checkout base ref for PRs, or actual branch for pushes
          ref: ${{
            (github.event_name == 'pull_request' && github.base_ref)
            || github.ref
            }}

      - name: Merge PR branch to PR target
        if: ${{ github.event_name == 'pull_request' }}
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git merge "origin/$HEAD_BRANCH"

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Build & Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_BUILD_MODE: |
            ${{
              (github.event_name == 'push' && github.ref_name) ||
              (github.event_name == 'pull_request' && github.base_ref == 'next' && github.base_ref) ||
              (github.event_name == 'pull_request' && format('{0}-{1}', 'pr', github.event.pull_request.number)) ||
              github.ref_name
            }}
          VITE_GITHUB_ACTOR: ${{ github.actor }}
          VITE_GITHUB_EVENT_NAME: ${{ github.event_name }}
          VITE_GITHUB_REPOSITORY: ${{ github.repository }}
          VITE_GITHUB_REF: ${{ github.ref }}
          VITE_GITHUB_SHA: ${{ github.sha }}
          VITE_GITHUB_HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          VITE_GITHUB_WORKFLOW: ${{ github.workflow }}
          VITE_GITHUB_WORKFLOW_REF: ${{ github.workflow_ref }}
          VITE_GITHUB_WORKFLOW_SHA: ${{ github.workflow_sha }}
          VITE_GITHUB_RUN_ID: ${{ github.run_id }}
          VITE_GITHUB_RUN_NUMBER: ${{ github.run_number }}
          VITE_GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
          VITE_BUILD_MACHINE_NAME: ${{ runner.name }}
          VITE_BUILD_OS: ${{ runner.os }}
          VITE_BUILD_OS_VERSION: ${{ runner.os-version }}
          VITE_BUILD_ARCH: ${{ runner.arch }}
          VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            unset GITHUB_ACTIONS
            npx semantic-release \
              --dry-run \
              --no-ci | \
              tee /tmp/semantic-release-raw.txt
            RAW_VERSION=$(grep -oP '(?<=Release note for version )[^:]+' /tmp/semantic-release-raw.txt)
            echo "RAW_VERSION=$RAW_VERSION"
            PREVIEW_VERSION="$RAW_VERSION-pr.${{ github.event.pull_request.number }}.${{ github.run_number }}"
            echo "preview-version=$PREVIEW_VERSION"
            echo "preview-version=$PREVIEW_VERSION" >> $GITHUB_OUTPUT
            npm version "$PREVIEW_VERSION" --no-git-tag-version
            jq -r '.version' package.json  # sanity check
            npm run prepare:tarball
          else
            npx semantic-release
          fi
        # Reuse the artifact for downstream deploy
      - name: Upload dist.tgz as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-tgz
          path: dist.tgz
          if-no-files-found: error

      - name: prepare semantic-release output for comment
        if: ${{ github.event_name == 'pull_request' }}
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
        run: |
          sed -n \
            -e '1,/Release note for version/d; p' \
            /tmp/semantic-release-raw.txt \
          | sed -E \
            -e  's/^[[:space:]]*\*/\*/' \
          | sed \
            -e "1s|\(\.\.\.[^)]*\))|...${HEAD_BRANCH} )|" \
            -e "1s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/$(date -u '+%Y-%m-%dT%H:%M UTC')/" \
            -e "1s/^# /## /" \
          | sed '1s/^/# Expected version change and release notes:\n/' \
          > /tmp/semantic-release-clean.txt

          if [ ! -s /tmp/semantic-release-clean.txt ]; then
            echo "# Expected version change and release notes" \
              > /tmp/semantic-release-clean.txt
            echo "## 🚨 WARNING: This PR is not expected to trigger a new version" \
              >> /tmp/semantic-release-clean.txt
            echo "To trigger a version bump, use at least one conventional commit message in this branch." \
              "See: https://www.conventionalcommits.org/en/v1.0.0/" \
              >> /tmp/semantic-release-clean.txt
          fi

      - name: preview semantic-release output for comment
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cat /tmp/semantic-release-clean.txt

      - name: Find Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "# Expected version change and release notes:"

      - name: Create or update comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: /tmp/semantic-release-clean.txt
          edit-mode: replace
