---
on:
  pull_request:
    branches:
      - "hotfix/**"
      - "release/**"
      - main
      - production
  push:
    branches:
      - "hotfix/**"
      - "release/**"
      - main
      - production

name: Node Package Checks
concurrency: node-package-checks

jobs:
  linting:
    name: "Run ESLint and Prettier checks"
    uses: ./.github/workflows/node-lint.yml

  test:
    name: "Run node unit tests"
    uses: ./.github/workflows/node-test.yml
