---
on:
  pull_request:
    branches:
      - main
      - production
      - next
  push:
    branches:
      - main
      - production

name: Node Package Checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ github.event_action }}
  cancel-in-progress: true

jobs:
  linting:
    name: "Linting"
    uses: ./.github/workflows/node-lint.yml

  formatting:
    name: "Formatting"
    uses: ./.github/workflows/node-prettier.yml

  unit-test:
    name: "Unit Tests"
    uses: ./.github/workflows/node-test.yml

  json-schema:
    name: "JSON Schema Validation"
    uses: ./.github/workflows/node-json-schema.yml

  build-release:
    name: "Build and Release"
    uses: ./.github/workflows/node-build_release.yml
    secrets: inherit

  deploy:
    name: "Deploy to SWA"
    if: ${{ needs.build-release.outputs.has_artifact }}
    needs: [build-release]
    uses: ./.github/workflows/azure-static-web-apps-deploy.yml
    secrets: inherit

  scan:
    name: "Check for forbidden patterns"
    uses: ./.github/workflows/admin-forbidden-patterns.yml
